### ISSUE TITLE
@extend within placeholder

### ISSUE THREAD

**Issue by rtsao** [travco/postcss-extend#1]
It appears `@extend` within a placeholder is currently unsupported, for example:

Input:
```sass
%foo {
  background: pink;
}

%bar {
  @extend: foo;
  font-size: 12px;
}

.baz {
  @extend %bar;
  color: orange;
}
```

Desired output:
```css
.baz {
  background: pink;
  font-size: 12px;
  color: orange;
}
```

Actual output:
```css
.baz {
  @extend: foo;
  font-size: 12px;
}

.baz {
  color: orange
}
```

Any thoughts on this?
