### ISSUE TITLE
Infinite loop

### ISSUE THREAD

**Issue by komlev** [travco/postcss-extend#12]
This code sends plugin into infinite loop
```css
.button {
  all: initial;
  cursor: pointer;
  font-size: 16px;
  padding: 10px 16px;
  border-radius: 2px;
}

.button_state_active {}

.button_state_hover {}

.button_state_focus {}

.button_state_disabled {
  cursor: default !important;
}

.button:hover:not(.button_state_disabled) {
  @extend .button_state_hover;
}

.button:focus:not(.button_state_disabled) {
  @extend .button_state_focus;
}

.button:active:not(.button_state_disabled) {
  @extend .button_state_active;
}

.button_state_hover {
  color: #FFF;
}

.button_state_active {
  color: #FFF;
}

.button_state_focus {

  @extend .button_state_hover;
}

.button_state_disabled {
  background-color: disabled(#FFF);
}

.button_size_smaller {
  padding: 4px 16px;
}
```
