### ISSUE TITLE
Pseudo-classes problem

### ISSUE THREAD

**Issue by komlev** [travco/postcss-extend#13]
There could be only one pseudo class:

```css
.foo:before {
  color: #111;
}

.bar:before {
  @extend .foo;
}
```

Will produce:
```css
.foo:before, .bar:before:before {
  color: #111;
}
```

I guess it has to omit one of the pseudo classes.
