### ISSUE TITLE
Extend not extending

### ISSUE THREAD

**Issue by stephenway** [travco/postcss-extend#17]
For some reason this specific extend selector does not extend to any selector I try to. Thoughts?
```css
.hide,
[hidden],
%hide { display: none !important; }

.foo { @extend %hide; }
```
Result is an empty file.

Another example that does not work for me:

```css
%hide { display: none !important; }

.foo { @extend %hide; }
```
