### ISSUE TITLE
[Question] Media in extends

### ISSUE THREAD

**Issue by Secretmapper** [travco/postcss-extend#21]
It seems that extend can only contain declarations and comments. How should I then do something similar to this:

```
@define-extend container {
  padding-top: 1em;
  padding-left: 15px;
  padding-right: 15px;
  @media (--md-viewport) {
    padding-left: 2em;
    padding-right: 2em;
  }
}
```

**Comment by travco** [comment]
Extend, as a general rule doesn't appreciate you nesting things, especially in the [placeholder-strict form (@define-extend)](https://github.com/travco/postcss-extend#defining-placeholders). If you wanted to be able to [extend placeholders inside `@media`](https://github.com/travco/postcss-extend#extending-something-inside-media-on-the-outside-looking-in), you need to separate it out a little bit. So assuming I'm not misinterpreting what you want:
```css
%container {
  padding-top: 1em;
  padding-left: 15px;
  padding-right: 15px;
}
@media (--md-viewport) {
  %container {
    padding-left: 2em;
    padding-right: 2em;
  }
 }
.extendingClass {
  color: gray;
  @extend %container;
}
```

Would resolve to:
```css
.extendingClass {
  padding-top: 1em;
  padding-left: 15px;
  padding-right: 15px;
}
@media (--md-viewport) {
  .extendingClass {
    padding-left: 2em;
    padding-right: 2em;
  }
 }
.extendingClass {
  color: gray;
}
```

Also - thank you, I realized the documentation on the limited scope (root-only) of `@define-placeholder` was a little lacking. Hope it helps.
