### ISSUE TITLE
Invalid CSS when using postcss-extend with postcss-nested, regardless of load order.

### ISSUE THREAD

**Issue by Blindmikey** [travco/postcss-extend#25]
Test postcss:

``` css
%testext { color: blue; }

.testrule
{
    &_subrule { @extend %testext; }
}
```

resulting css

``` css
&_subrule { color: blue; }
```

expected css

``` css
.testrule_subrule { color: blue; }
```
