### ISSUE TITLE
Error when @extend after @extend 

### ISSUE THREAD

**Issue by jessehattabaugh** [travco/postcss-extend#6]
When I extend a placeholder that extends another placeholder at the same time as any other placeholder, I get an empty output file and no error

```css
%foo {
  color: blue;
}
%bar {
  font-size: 12px;
}
%baz {
  @extend %bar;
  background: red;
}

.bam {
  @extend %foo;
  @extend %baz;
}

/* Result Empty */
```

@extending placeholders that @extend usually works just fine, just not at the same time as other @extends

```css
.bam {
    @extend %baz;
}

/* Result */

.bam {
    font-size: 12px;
}
.bam {
    background: red;
}
```
