### ISSUE TITLE
Extend silent imports?

### ISSUE THREAD

**Issue by Dylan-Chapman** [travco/postcss-extend#9]
Hello,

I'm trying to accomplish something similar to what I had in my Stylus files where I would silently import a file (I don't want all of the code in the file, I just want to extend a few things that are inside of it).

I want to do something similar to the following:

```css
%icons {
    @import "components/icons.css"
}
```

And within icons.css I have:

```css
@define-mixin icon $name, $content {
    .$name:before {
        content: $content;
    }

    %$name {
        content: $content;
    }
}

@mixin icon icon-add, "\e069";
@mixin icon icon-arrow-left, "\e200";
@mixin icon icon-arrow-right, "\e204";
...etc
```

Which essentially creates a concrete class for use in HTML, and an extendable placeholder class for use in CSS.

So, now I'd like to be able to call:

```css
.test:before {
    @extend %icons %icon-add;
}
```

This doesn't seem to work, however, as I get the error "'%icons %icon-add', has not been defined, so it cannot be extended."

Is this possible and I'm doing something incorrectly? Is there a better way to accomplish what I want to do?

Thanks.

**Comment by Dylan-Chapman** [comment]
Okay, so I see the problem. As described above, this can't be done if postcss-extend comes before postcss-nested. However, postcss-extend HAS to come first according to the PSA on this plugin's page (and from my testing). Is there a way to get the best of both worlds here or am I out of luck?

**Comment by travco** [comment]
Because of the way the plugin is implemented - putting in `@extend %icons %icon-add;` will make the plugin look for some css rule that is `%icons %icon-add { /*something something;*/ }`. 

Try seperating it out into 
```css
@extend %icons;
@extend %icons-add;```

It's a little tedious, but it saves some of the nightmare of trying to parse what people mean.

**Comment by Dylan-Chapman** [comment]
This gives a very strange output.

Input:

```css
/* icons.css */
@define-mixin icon $name, $content {
    .$name:before {
        content: $content;
    }

    %$name {
        content: $content;
    }
}

@mixin icon icon-add, "\e069";
@mixin icon icon-arrow-left, "\e200";
@mixin icon icon-arrow-right, "\e204";
```
```css
%icons {
    @import "components/icons.css";
}

.test:before {
    @extend %icons;
    @extend %icon-add;
}
```

Output:
```css
.test:before .icon-add:before,.test:before .test:before {
    content: "\e069"
}

.test:before .icon-arrow-left:before {
    content: "\e200"
}

.test:before .icon-arrow-right:before {
    content: "\e204"
}
```

Desired output:

```css
.test:before {
    content: "\e069"
}
```
